spring:
  profiles:
    active:
     -dev
---
spring:
 profiles:dev
 application:
   name:microservicecloud-config-bjyt-dev
---
spring:
  profiles:test
  application:
    name:microservicecloud-config-bjyt-test