spring:
  profiles:
    active:
    -dev
---
server:
  port:8001
spring:
  profiles:dev
  application:
    name:microservicecloud-config-dept-client
  datasoure:
    type:com.alibaba.druid.pool.DruidDataSource
    driver-class-name:com.mysql.jdbc.Driver
    url:jdbc:mysql://localhost:3306/fund1?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username:root
    password:root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
mybatis:
    config-location:classpath*:mybatis/mybatis.cfg.xml
    type-aliases-package:com.bjyt.springcloud.entity
    mapper-locations:
    -classpath*:mybatis/mapper/*.xml
eureka:
    client:
      service-url:
        defaultZone:http://eureka7001.com:7001/eureka
---
server:
  port:7001
spring:
  profiles:test
  application:
    name:microservicecloud-config-eureka-client
datasoure:
    type:com.alibaba.druid.pool.DruidDataSource
    driver-class-name:com.mysql.jdbc.Driver
    url:jdbc:mysql://localhost:3306/fund2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
    username:root
    password:root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
mybatis:
    config-location:classpath*:mybatis/mybatis.cfg.xml
    type-aliases-package:com.bjyt.springcloud.entity
    mapper-locations:
    -classpath*:mybatis/mapper/*.xml
eureka:
 instance:
   hostname:eureka7001.com
 client:
   register-with-eureka:false
   fetch-registry:false
   service-url:
     defaultZone:http://eureka7001.com:7001/eureka/
   
    