spring:
    profiles:
        active
        - dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-dev-8201-update
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservicecloud-config-client-test-8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
