spring:
  profiles:
    active:
     - dev
---

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client
    
server:
  port: 1001
  
eureka:
  instance:
    hostname: eureka1001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:1001/eureka/
  